# This is a basic workflow to help you get started with Actions

name: 3D-Staging

# Controls when the action will run. 
on:    
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
          repository: aspose-cloud/products.aspose.cloud
          token: ${{ secrets.REPO_TOKEN }}
          fetch-depth: 0
    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
          hugo-version: 0.110.0
          extended: true

    - name: Install Dependicies1
      run:  npm install -D --save autoprefixer

    - name: Install Dependicies2
      run:  npm install -D --save postcss-cli

    - name: Find and Replace
      uses: jacobtomlinson/gha-find-replace@v2
      with:
        find: "url:"
        replace: "url_ignore:"
        include: "_index.md" # Will match all .md files in any nested directory

    - name: Find and Replace domain name
      uses: jacobtomlinson/gha-find-replace@v2
      with:
        find: "products.aspose.cloud"
        replace: "products-qa.aspose.cloud"
        include: "_index.md" # Will match all .md files in any nested directory      
    
    - name: Build 3d
      run: hugo --config "./config-stage.toml" -c "content/3d" -b "https://products-qa.aspose.cloud/3d" --cleanDestinationDir --minify
    
    - name: Deploy 3d to S3
      run: hugo deploy --config "./config-stage.toml" --target "3d" --maxDeletes -1  --force
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS }}
