name: Slides-Production

# Controls when the action will run. 
on:    
  workflow_dispatch:
jobs:
  deploy:
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
          repository: aspose-cloud/products.aspose.cloud
          token: ${{ secrets.REPO_TOKEN }}
          fetch-depth: 0
    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
          hugo-version: '0.101.0'
          extended: true

    - name: Install autoprefixer
      run:  npm install -D --save autoprefixer

    - name: Install postcss-cli
      run:  npm install -D --save postcss-cli

    - name: Find and Replace
      run: LC_ALL=C find . -type f -name '*.md' -exec sed -i '' s/url:/url_ignore:/g {} +
    
    - name: Build Slides
      run: hugo --config "./config/slides-prod.toml" -c "content/slides" -b "https://products.aspose.cloud/slides" --cleanDestinationDir --minify
    
    - name: Deploy Slides to S3
      run: hugo deploy --config "./config/slides-prod.toml" --target "slides" --maxDeletes -1  --force
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS }}
